log-attempts: false
# Set log-attempts to true if u want to log every attempt to use the exploit in console
punish-command: ""
#Command to run if someone attempts to abuse the exploit, supports PAPI placeholders, don't include the slash in the command, use %player% for to target the player if you don't have PlaceholderAPI or the Player expansion for it
punish-on-attempt: false